name: Publish Built package to a branch
description: Build each commit and publish to a branch
inputs:
  pack-command:
    description: 'Command to generate the package tarball'
    required: false
    default: 'npm pack'
  branch:
    description: 'Branch name to publish to'
    required: false
    default: 'dist'
  token:
    description: 'A Github token with write access to the repository'
    required: true
  working-directory:
    description: 'Directory in which to run the pack command'
    required: false
    default: './'

runs:
  using: "composite"
  steps:
    - name: 'Pack'
      shell: 'bash'
      run: ${{ inputs.pack-command }}
      working-directory: ${{ inputs.working-directory }}
    - name: 'Make tmpdir'
      shell: 'bash'
      run: mkdir -p tmp/dist-action
      working-directory: ${{ inputs.working-directory }}
    - name: 'Unpack'
      shell: 'bash'
      run: tar -xvzf *.tgz -C tmp/dist-action
      working-directory: ${{ inputs.working-directory }}
    - name: 'Upload published package contents to branch'
      shell: 'bash'
      run: |
        cd tmp/dist-action/package
        git config --global init.defaultBranch main
        git init
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Publish dist for ${{ github.sha }}"
        git push --force "https://${GITHUB_ACTOR}:${{ inputs.token }}@github.com/${{ github.repository }}" main:${{ inputs.branch }}
      working-directory: ${{ inputs.working-directory }}
