name: Build dist

on:
  push:
    branches:
      - main
      - master

jobs:
  build-dist:
    name: Build dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - uses: kategengler/put-built-npm-package-contents-on-branch@v0.0.1
        with:
          branch: dist
          token: ${{ secrets.PAT }}
          working-directory: ember-resources
